# Theoretical Questions

### 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

In [ ]:
# SOLUTION :-
'''
1- Purpose - Its purspose is to provide :

             a-Efficient numerical computation
             
             b-Mullti dimensional array data structure
             
             c-Vectorized operations
             
             d-Integration  with other scientific libraries 

2- Advantages - Speed : Numpy's optimized c code provides faster computation than native Python

                Memory efficiency : Numpy array store data compactly reducing memory usgae
                
                Broadcasting : Easily perform operations on arrays with different shapes
                
                Integration : Seamlessly integrates with other scientific libraries
                
                Community : Large , active community contributes to numpy development and support

'''
# It enhances python capability for numerical operations in  several ways
'''
1-Advanced mathematical functions : Linear algebra  , Statsticial funcions , Random number generation 

2- optimized c code : numpy core is written in c it provides faster execution than native python

3- Integration with other libraries : It integrates with scipy , pandas and matplotlib

4- Efficient arrays : Replaces python list with optimized homogeneous array 


### 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [ ]:
# np.mean() and np.average() are two related but distinct functions in numpy for calculating central tendency of an array
'''
1- np.mean igonre NaNs by default 
   np.average propagates NaNs by default 

2- np.mean calculates the arithmetic mean 
   np.average calculates the weighted average

Both support multidimensional arrays
Both calculate central tendency of an array 
'''

# We use  np.mean for calculating simple average and ignoring Nan 
# example 
np.mean(np.array([1,2,3,4]))
ouput will be 2.5

# We use np.average for calculating weighted average and preserving NaN
#example
np.average(np.array([1,2,3,4]))
outout will be #NAN propogates NaN

### 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays

In [30]:
# Reversing can be achieved using np.flip() or np.revers() function 
# in np.reverse() no axis specifie
# np.flip() specific axis 
# EXAMPLE
import numpy as np
a=np.array([1,2,3,4,5])
print('----------------')
print(a,"Dimensions:-",a.ndim)
print('----------------')
print(np.flip(a))
print('----------------')
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b,"Dimensions:",b.ndim)
print(np.flip(b,axis=0))
print('----------------')
print(np.flip(b,axis=1))

----------------
[1 2 3 4 5] Dimensions:- 1
----------------
[5 4 3 2 1]
----------------
[[1 2 3 4]
 [5 6 7 8]] Dimensions: 2
[[5 6 7 8]
 [1 2 3 4]]
----------------
[[4 3 2 1]
 [8 7 6 5]]


### 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance

In [34]:
# We can determine data type by using np.array.dtype
#Example 
a=np.array(['a','b','c'])
print(a, "data type:-",a.dtype)
b=np.array([1,2,3,4])
print(b, "data type:-",b.dtype)

['a' 'b' 'c'] data type:- <U1
[1 2 3 4] data type:- int32


In [ ]:
'''
Data type determines the amount of memory allocated for each variable  

Larger data type consume more memory , leading to memory exhaustion 

Data alignment ensures efficient memory access and reduces memory waste 

Data types affect cache line alignment and utilization 

It impacts data transfer rates between memory and CPU
'''

### 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [ ]:
'''
An ndarray is a homogeneous multi dimensional collection of values , where each value has the same data type 
'''
'''
Key features -  Multi Dimensionality - ndarray can have any number of dimensions


                Homogeneous - All elements have the same data type

                Flexible data type - Supports various data types

                Dynamic reshaping  - Can be reshape without copying data
'''
'''
Python list :general purpose programming , storing heterogeneous data
Numpy arrays : Scientific computing , data analysis , machine learning , image processing 
Performance - Numpy array provide faster element wise operation due to vectorization 
Mutability - Both numpy array and python list are mutable
Reshape -Array can be reshape without copying data

### 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [ ]:
'''
Use numpy array for numerical operations numpy operations are implemented in c code

It supports parallel operations using multi threading and multi processing 

Numpy arrays store data contiguously , minimizing memory access over head
'''
'''
if we are performing addition in numpy array then execution time will be 12.6 msc 

while in list execution time will be 1.35 sec

numpy array speed up data cleaning,filtering, and aggregation 
'''

### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In [ ]:
'''
Orientation - vstack () - stacks arrays vertically (row wise) 
              hstack () - stacks arrays horizontally (column wise)

Axis - vstack() - concatenates along axis=0
       hstack() - concatenates along axis=1

 vstack()- It increases number of rows 
 hstack() - It increases number of columns
'''

In [44]:
# Example 
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('----------------')
n=np.vstack(a)
print("Vertical stacking ")
print(n)
print('----------------')
x=np.hstack(a)
print("Horizontal stacking ")
print(x)

[[1 2 3]
 [4 5 6]]
----------------
Vertical stacking 
[[1 2 3]
 [4 5 6]]
----------------
Horizontal stacking 
[1 2 3 4 5 6]


### 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In [ ]:
# fliplr()
'''

it flips array horizontally (left-right) 

flips along axis=1 (columns)

'''
# flipud()
'''

it flips array vertically (up down)

flips along axis=0 (rows)

'''

# FOR 1D ARRAY - fliplr() and flipud() HAVE THE SAME EFFECT  :  IT WILL REVERSE ARRAY 

# FOR 2D ARRAY - fliplr() : FLIPS HORIZONTALLY (COLUMNS) ,flipud() : FLIP VERTICALLY  (ROWS)

# FOR 3D ARRAY - fliplr() : FLIP HOTHORIZONTALLY (COLUMNS) ALONG AXIS=1 , flipud() : FLIP VERTICALLY  (ROWS) ALONG AXIS=0

### 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [ ]:
'''
It splits an array into multiple sub-arrays 

It allpws specification of the axis to split along 

It handles uneven split by distributing remaining elements

'''
'''
It handles uneven splits by distributing the remaining elements among the sections 

If indices or split is an array like, split points must be specified explicitly

'''

### 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [ ]:
# Vectorization :-
'''
It is the process of applying operations to entire array at once , without the need for explicit loops 

Benefit - 

a- Faster execution 

b- Concise code

c- Improved readability

Shapes should be equal 
'''
# Broadcasting :- 
'''
It is the process of aligning arrays with different shapes and sizes for operations

Rules - if shapes are equal , no broadcastinng occurs

       If shapes are incompatible , a value error is raised 
'''

# Vectorization contribution 
'''
Faster execution - operations are faster than looping over individual elements

concise code - reduce code length and improve readability

improved memory management - minimize memory allocation

parallelization - Take advantage of multi core processors
'''
# Broadcasting contribution 
'''
Flexible array alignment - allows array with different shapes to be aligned for operations 

Eficient memory usage - minimizes memory allocation and copying

simplified code - reduces the need for explicit looping and indexing 

Enhanced Expressiveness - enables complex operations to be expressed concisely
'''

## PRACTICAL QUESTIONS

In [10]:
import numpy as np
import random

### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [4]:
# SOLUTION :-

In [30]:
arr=np.random.randint(1,100,(3,3))
print("original array")
print("----------------")
print(arr)

original array
----------------
[[55 11 85]
 [14 32 56]
 [66 88 34]]


In [32]:
transpose=arr.T
print("transposed array")
print("---------------")
print(transpose)

transposed array
---------------
[[55 14 66]
 [11 32 88]
 [85 56 34]]


### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [35]:
# SOLUTION :-

In [43]:
arr1=np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
# RESHAPING  IT INTO 2X5 ARRAY
x=arr1.reshape(2,5)
print("2x5 array")
print("-------------")
print(x)

2x5 array
-------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [53]:
# RESHAPING IT INTO 5X2 ARRAY
y=arr1.reshape(5,2)
print("5x2 array")
print("-------------")
print(y)

5x2 array
-------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [57]:
# SOLUTION :-

In [69]:
arr2=np.random.rand(4,4)
print(arr2)
print("------------------")
print(arr2.shape)

[[0.287751   0.30396765 0.58492774 0.69706699]
 [0.55770281 0.58350234 0.51656496 0.92450408]
 [0.87411805 0.62813061 0.7457788  0.89459938]
 [0.03023781 0.46506781 0.09350051 0.97329021]]
------------------
(4, 4)


In [92]:
border=np.pad(arr2,1)
print("border of zeros")
print("-------------------")
print(border)
print("------------------")
print(border.shape)

border of zeros
-------------------
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.287751   0.30396765 0.58492774 0.69706699 0.        ]
 [0.         0.55770281 0.58350234 0.51656496 0.92450408 0.        ]
 [0.         0.87411805 0.62813061 0.7457788  0.89459938 0.        ]
 [0.         0.03023781 0.46506781 0.09350051 0.97329021 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
------------------
(6, 6)


### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [72]:
# SOLUTION :-

In [76]:
arr3=np.arange(10,60,5)
print(arr3)

[10 15 20 25 30 35 40 45 50 55]


### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations.

### (uppercase, lowercase, title case, etc.) to each element

In [84]:
# SOLUTION :-

In [88]:
st=['python','numpy','pandas']
arr4=np.array(st)
print(arr4)

['python' 'numpy' 'pandas']


In [94]:
up=np.char.upper(arr4)
print("Uppercase")
print(up)

Uppercase
['PYTHON' 'NUMPY' 'PANDAS']


In [102]:
cap=np.char.capitalize(arr4)
print("First word of each word is uppercase")
print(cap)

First word of each word is uppercase
['Python' 'Numpy' 'Pandas']


In [100]:
print(up)
print("-------------")
print("lowercase")
lo=np.char.lower(up)
print(lo)

['PYTHON' 'NUMPY' 'PANDAS']
-------------
lowercase
['python' 'numpy' 'pandas']


In [106]:
print(lo)
print("----------------")
n=np.char.title(lo)
print("both capitalize and title works same")
print("-----------------------------------")
print(n)

['python' 'numpy' 'pandas']
----------------
both capitalize and title works same
-----------------------------------
['Python' 'Numpy' 'Pandas']


### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [109]:
# SOLUTION :-

In [111]:
li=['ramesh','apple','banana','suresh','cherry']
ins=np.array(li)
print(ins)

['ramesh' 'apple' 'banana' 'suresh' 'cherry']


In [125]:
# using list comprehension 
space=[" ".join(i)for i in ins] 

In [127]:
print("list comprehension iterates over each word ")
print("-----------------------------------------------")
print(space)

list comprehension iterates over each word 
-----------------------------------------------
['r a m e s h', 'a p p l e', 'b a n a n a', 's u r e s h', 'c h e r r y']


### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [131]:
# SOLUTION :-

In [141]:
arr5=np.array([[1,2,3,4,5,6]])
arr6=np.array([[7,8,9,10,11,12]])
print(arr5)
print("--------------")
print(arr6)

[[1 2 3 4 5 6]]
--------------
[[ 7  8  9 10 11 12]]


In [161]:
a=arr5.reshape(3,2)
print(a)
print("---------------")
print(b)
b=arr6.reshape(3,2)

[[1 2]
 [3 4]
 [5 6]]
---------------
[[ 7  8]
 [ 9 10]
 [11 12]]


In [186]:
print("addition")
print("-----------")
np.add(a,b)

addition
-----------


array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [188]:
print("subtraction")
print("-----------")
np.subtract(a,b)

subtraction
-----------


array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [190]:
print("multiplication")
print("-----------")
np.multiply(a,b)

multiplication
-----------


array([[ 7, 16],
       [27, 40],
       [55, 72]])

In [192]:
print("division")
print("-----------")
np.mod(a,b)

division
-----------


array([[1, 2],
       [3, 4],
       [5, 6]])

### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [195]:
# SOLUTION :-

In [255]:
mat=np.random.randint(1,21,(5,5))
mat
a=np.matrix(mat)

In [269]:
n=type(a)
print(n)
print('--------------')
print(a)
print('---------------')
print("diagonal elements")
print('--------------')
print(np.diag(a))
print(np.diag(np.fliplr(a)))

<class 'numpy.matrix'>
--------------
[[17  7  8 20  4]
 [17 14 11 18 12]
 [18  1 16  8 10]
 [ 4 17 10  2  5]
 [18 18  9 11 10]]
---------------
diagonal elements
--------------
[17 14 16  2 10]
[ 4 18 16 17 18]


### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in  this array

In [273]:
# SOLUTION :-

In [295]:
arr7=np.random.randint(0,1000,100)
pr=[]
for i in arr7:
    a=True
    if i<2:
        a=False
    else:
        for j in range(2,int(i**0.5)+1):
            if i %j==0:
                a=False
                break
    if a:
        pr.append(i)
print("Random number")
print(arr7)
print("--------------------------")
print("Prime numbers:",pr)

Random number
[272 517 207  52 437 804 306 129 331 685 615 552 776 662 455 332 257 655
 531 593 853 848 607 268 207 648 564 874 795 268 841 305 163 619   5  66
 202 785 592 730 978 375 892 272 896 684 465 535 968 786 675 338 808 847
 481 487 889 546 549  85 429 465  76 251 797  39 496 928 502 756 153 538
   7 528 701 620 876 536 256 593 297 811 490 118 191 459 186  28  15 365
 181 580 341 270 449 267 715 904 905 121]
--------------------------
Prime numbers: [331, 257, 593, 853, 607, 163, 619, 5, 487, 251, 797, 7, 701, 593, 811, 191, 181, 449]


### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [307]:
print("In celcius")
a=np.array([12,14,15,18,20,16,22,
   20,19,23,24,25,26,25,
   25,24,24,23,23,24,25,
   25,26,27,27,25,26,27])
re=n.reshape(4,7)

In celcius


In [311]:
avg=np.mean(re,axis=1)
print("Temperature data of a month ")
print("--------------------------")
print(re)
print('----------------')
print('Weekly Average')
print('------------')
avg

Temperature data of a month 
--------------------------
[[12 14 15 18 20 16 22]
 [20 19 23 24 25 26 25]
 [25 24 24 23 23 24 25]
 [25 26 27 27 25 26 27]]
----------------
Weekly Average
------------


array([16.71428571, 23.14285714, 24.        , 26.14285714])